dist: xenial

language: minimal

install:
  - echo $(echo "${SSH_KEY}" | base64 --decode) > $HOME/.ssh/project_key
  - chmod 400 $HOME/.ssh/project_key
  - git clone https://github.com/docksal/bats.git tests/scripts/bats
  - cd tests/scripts/bats
  - sudo ./install.sh /usr/local
  - cd "$TRAVIS_BUILD_DIR"
  - sudo cp ./bin/fin /usr/local/bin/fin
  - fin version
  - USE_BRANCH="${TRAVIS_BRANCH}"
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" && "${TRAVIS_PULL_REQUEST_SLUG}" == "${TRAVIS_REPO_SLUG}" ]]; then USE_BRANCH="${TRAVIS_PULL_REQUEST_BRANCH}"; fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" && "${TRAVIS_PULL_REQUEST_SLUG}" != "${TRAVIS_REPO_SLUG}" ]]; then USE_BRANCH='develop'; fi
  - export DOCKSAL_VERSION=${USE_BRANCH}
  - export SKIP=1
  - fin update
  - fin sysinfo

before_script:
  - git clone https://github.com/docksal/drupal8.git ../drupal8
  - mkdir ../test-config
  - mkdir ../test-duplicates
  - mkdir ../test-init
  - mkdir ../test-db
  - mkdir ../test-pull
  # Function runs tests by file name $1 in dir specified in $2
  - run_tests() { cd "${2:-$TRAVIS_BUILD_DIR}"; [[ "$TRAVIS_COMMIT_MESSAGE" =~ "[quick-test]" && "$1" != "quicktest.bats" ]] && return; [[ "$1" == "quicktest.bats" ]] && I="-i"; bats ${I} "$TRAVIS_BUILD_DIR/tests/$1"; }
  # Trigger builds in boilerplate project repos
  - build_trigger() { [[ "$TRAVIS_BRANCH" == "master" ]] && cd "$TRAVIS_BUILD_DIR" && tests/scripts/travisci-build-trigger "$1"; }
  - echo "Running tests..."

script:
  - run_tests system.bats
  - run_tests config.bats "$TRAVIS_BUILD_DIR/../test-config"
  - run_tests general.bats "$TRAVIS_BUILD_DIR/../drupal8"
  - run_tests db.bats "$TRAVIS_BUILD_DIR/../test-db"
  - run_tests duplicates.bats "$TRAVIS_BUILD_DIR/../test-duplicates"
  - run_tests quicktest.bats
  - run_tests pull.bats "$TRAVIS_BUILD_DIR/../test-pull"

after_success:
  - build_trigger docksal/drupal7
  - build_trigger docksal/drupal7-advanced
  - build_trigger docksal/drupal8
  - build_trigger docksal/wordpress
  - build_trigger docksal/magento
  - build_trigger docksal/magento-demo
